// Generated by CoffeeScript 1.10.0
(function() {
  var menuJSON;

  menuJSON = [
    {
      "name": "Comics",
      "href": "#comics",
      "icon": '<i class="fa fa-newspaper-o" aria-hidden="true"></i>',
      "type": "parent",
      "depth": [
        {
          "name": "xkcd",
          "id": "xkcd",
          "icon": '<img src="https://dl.dropbox.com/s/s2eqegrcbkm3e9k/xkcd.png" alt="xkcd"></img>',
          "type": "modal"
        }, {
          "name": "Robot Hugs",
          "id": "robot-hugs",
          "icon": '<img src="https://dl.dropbox.com/s/kj16vh46gxysxsl/robot-hugs.png" alt="Robot Hugs"></img>',
          "type": "modal"
        }, {
          "name": "The New York Daily Cartoon",
          "id": "nydc",
          "icon": '<img src="https://dl.dropbox.com/s/t9hk4l2kbne0te5/nydc.png" alt="The New York Daily Cartoon"></img>',
          "type": "modal"
        }, {
          "name": "Dilbert",
          "id": "dilbert",
          "icon": '<img src="https://dl.dropbox.com/s/2d3mt36ls6rpfn6/dilbert.png" alt="Dilbert"></img>',
          "type": "modal"
        }, {
          "name": "Garfield",
          "id": "garfield",
          "icon": '<img src="https://dl.dropbox.com/s/675xwkiyvnh2s13/garfield.png" alt="Garfield"></img>',
          "type": "modal"
        }
      ]
    }, {
      "name": "Interests",
      "href": "#interests",
      "icon": '<i class="fa fa-th-large" aria-hidden="true"></i>',
      "type": "parent",
      "depth": [
        {
          "name": "Technology",
          "id": "tech",
          "icon": '<i class="fa fa-cogs" aria-hidden="true"></i>',
          "type": "modal"
        }, {
          "name": "Science",
          "id": "science",
          "icon": '<i class="fa fa-flask" aria-hidden="true"></i>',
          "type": "modal"
        }, {
          "name": "Education",
          "id": "ed",
          "icon": '<i class="fa fa-graduation-cap" aria-hidden="true"></i>',
          "type": "modal"
        }, {
          "name": "Photography",
          "id": "photo",
          "icon": '<i class="fa fa-camera-retro" aria-hidden="true"></i>',
          "type": "modal"
        }, {
          "name": "Travel",
          "id": "travel",
          "icon": '<i class="fa fa-space-shuttle" aria-hidden="true"></i>',
          "type": "modal"
        }, {
          "name": "Art",
          "id": "art",
          "icon": '<i class="fa fa-paint-brush" aria-hidden="true"></i>',
          "type": "modal"
        }
      ]
    }, {
      "name": "Miscellaneous",
      "href": "#paperclips",
      "icon": '<i class="fa fa-paperclip" aria-hidden="true"></i>',
      "type": "parent",
      "depth": [
        {
          "name": "My Playlist",
          "href": 'https://play.google.com/music/playlist/AMaBXylKskCXe8Z6-63NTWKiUCSI7dsvygl9nHI6O49b-nHbrwRfvPoW6PKH65GVGcC4BDP01L59uCys2-6mQ-ASduXCB2mw_Q==',
          "icon": '<i class="fa fa-headphones" aria-hidden="true"></i>',
          "type": "link"
        }, {
          "name": "Wishlists & Favourites",
          "href": "https://trello.com/b/OfGWqp2K",
          "icon": '<i class="fa fa-star-half-o" aria-hidden="true"></i>',
          "type": "link"
        }, {
          "name": "On Repeats",
          "id": "onrepeats",
          "icon": '<i class="fa fa-retweet" aria-hidden="true"></i>',
          "type": "modal"
        }
      ]
    }, {
      "name": "Dev Board",
      "href": "https://trello.com/b/bpMw7Bm1",
      "icon": '<i class="fa fa-terminal" aria-hidden="true"></i>',
      "type": "link"
    }
  ];

  window.onload = function() {
    var modal, sidebar;
    sidebar = new SideBar();
    modal = new Modal();
    $('#xkcd').click(function() {
      return modal.getXKCD();
    });
    $('#robot-hugs').click(function() {
      return modal.getRobotHugs();
    });
    $('#nydc').click(function() {
      return modal.getNYDC();
    });
    $('#dilbert').click(function() {
      return modal.getDilbert();
    });
    $('#garfield').click(function() {
      return modal.getGarfield();
    });
    $('#tech').click(function() {
      return modal.getTech();
    });
    $('#science').click(function() {
      return modal.getScience();
    });
    $('#ed').click(function() {
      return modal.getEducation();
    });
    $('#photo').click(function() {
      return modal.getPhotography();
    });
    $('#travel').click(function() {
      return modal.getTravel();
    });
    $('#art').click(function() {
      return modal.getArt();
    });
    return $('#onrepeats').click(function() {
      return modal.getOnRepeats();
    });
  };


  /*
    paperclips = new Paperclips()
    $('#playlist').click () ->
      paperclips.getPlaylist()
   */

  window.Modal = (function() {
    function Modal() {}

    Modal.prototype.getXKCD = function() {
      var url;
      $('.modal-title').empty();
      $('#comicModal').siblings().hide();
      $('#comicModal').empty();
      url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20where%20url%3D'http%3A%2F%2Fxkcd.com%2Finfo.0.json'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      return $.getJSON(url, function(res) {
        var alt, img, tag, title;
        console.log(res);
        img = res.query.results.json.img;
        title = res.query.results.json.title;
        alt = res.query.results.json.alt;
        tag = "<img src='" + img + "' alt='" + alt + "' />";
        $('.modal-title').prepend("xkcd: " + title);
        $('#comicModal').prepend(tag);
        return $('#comicModal').show();
      }, "jsonp");
    };

    Modal.prototype.getRobotHugs = function() {
      var url;
      $('.modal-title').empty();
      $('#comicModal').siblings().hide();
      $('#comicModal').empty();
      url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20rss%20where%20url%3D'http%3A%2F%2Fwww.robot-hugs.com%2Ffeed%2F'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      return $.getJSON(url, function(res) {
        var img, tag, title;
        img = res.query.results.item[0].p.a.img;
        title = res.query.results.item[0].title;
        tag = "<img src='" + img.src + "' alt='" + img.alt + "' />";
        $('.modal-title').prepend("Robot Hugs: " + title);
        $('#comicModal').prepend(tag);
        return $('#comicModal').show();
      }, "jsonp");
    };

    Modal.prototype.getNYDC = function() {
      var url;
      $('.modal-title').empty();
      $('#comicModal').siblings().hide();
      $('#comicModal').empty();
      url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20rss%20where%20url%20%3D%22http%3A%2F%2Fwww.comicsyndicate.org%2FFeed%2FThe%2520New%2520Yorker%2520Daily%2520Cartoon%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      return $.getJSON(url, function(res) {
        var tag;
        $('.modal-title').prepend("New York Daily Cartoon");
        tag = res.query.results.item[0].description;
        $('#comicModal').prepend(tag);
        return $('#comicModal').show();
      }, "jsonp");
    };

    Modal.prototype.getDilbert = function() {
      var url;
      $('.modal-title').empty();
      $('#comicModal').siblings().hide();
      $('#comicModal').empty();
      url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20rss%20where%20url%20%3D%22http%3A%2F%2Fwww.comicsyndicate.org%2FFeed%2FDilbert%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      return $.getJSON(url, function(res) {
        var tag;
        $('.modal-title').prepend("Dilbert");
        tag = res.query.results.item[0].description;
        $('#comicModal').prepend(tag);
        return $('#comicModal').show();
      }, "jsonp");
    };

    Modal.prototype.getGarfield = function() {
      var url;
      $('.modal-title').empty();
      $('#comicModal').siblings().hide();
      $('#comicModal').empty();
      url = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20rss%20where%20url%20%3D%22http%3A%2F%2Fwww.comicsyndicate.org%2FFeed%2FGarfield%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      return $.getJSON(url, function(res) {
        var tag;
        $('.modal-title').prepend("Garfield");
        tag = res.query.results.item[0].description;
        $('#comicModal').prepend(tag);
        return $('#comicModal').show();
      }, "jsonp");
    };

    Modal.prototype.getTech = function() {
      $('.modal-title').empty().prepend("Technology");
      $('#techModal').siblings().hide();
      return $('#techModal').show();
    };

    Modal.prototype.getScience = function() {
      $('.modal-title').empty().prepend("Science");
      $('#sciModal').siblings().hide();
      return $('#sciModal').show();
    };

    Modal.prototype.getEducation = function() {
      $('.modal-title').empty().prepend("Education");
      $('#edModal').siblings().hide();
      return $('#edModal').show();
    };

    Modal.prototype.getPhotography = function() {
      $('.modal-title').empty().prepend("Photography");
      $('#photoModal').siblings().hide();
      return $('#photoModal').show();
    };

    Modal.prototype.getTravel = function() {
      $('.modal-title').empty().prepend("Travel");
      $('#travelModal').siblings().hide();
      return $('#travelModal').show();
    };

    Modal.prototype.getArt = function() {
      $('.modal-title').empty().prepend("Art");
      $('#artModal').siblings().hide();
      return $('#artModal').show();
    };

    Modal.prototype.getOnRepeats = function() {
      $('.modal-title').empty().prepend("On Repeats");
      $('#onrepeatsModal').siblings().hide();
      return $('#onrepeatsModal').show();
    };

    return Modal;

  })();

  window.SideBar = (function() {
    function SideBar() {
      var i, len, m;
      for (i = 0, len = menuJSON.length; i < len; i++) {
        m = menuJSON[i];
        this.setMenuItem(m, '#sidebar', 0);
      }
    }

    SideBar.prototype.setMenuItem = function(item, href, level) {
      var indent;
      indent = "";
      if (level === 1) {
        indent = "sub-level-a";
      }
      if (item.type === "parent") {
        $(href).append("<a aria-controls=" + item.name + " aria-expanded='false' class='list-group-item " + indent + "' data-toggle='collapse' href=" + item.href + ">" + item.icon + " " + item.name + "</a><div class='collapse' id='" + (item.href.substr(1)) + "'></div>");
      } else if (item.type === "link") {
        $(href).append("<a class='list-group-item " + indent + "' href=" + item.href + "  target='_blank'>" + item.icon + " " + item.name + "</a>");
      } else {
        $(href).append("<a class='list-group-item " + indent + "' data-target='#focus' data-toggle='modal' id=" + item.id + ">" + item.icon + " " + item.name + "</a>");
      }
      if (item.depth) {
        return this.setSubMenu(item.depth, item.href, level);
      }
    };

    SideBar.prototype.setSubMenu = function(menu, href, level) {
      var i, len, m, results;
      results = [];
      for (i = 0, len = menu.length; i < len; i++) {
        m = menu[i];
        $(href).append("<div class='collapse' id=" + (href.substr(1)) + ">");
        results.push(this.setMenuItem(m, href, level + 1));
      }
      return results;
    };

    return SideBar;

  })();

}).call(this);
